import { type NextPage } from "next";
import Head from "next/head";
import Layout from "../../components/Layout";
import { trpc } from "../../utils/trpc";
import { RoomWithCreatorAndParticipants } from "../../types/models";
import Link from "next/link";

const Rooms: NextPage = () => {
  const rooms = trpc.room.getAll.useQuery();
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="container mx-auto py-16">
          <h1 className="text-2xl text-white">Browse Rooms</h1>
          <ul
            role="list"
            className="mt-5 grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3"
          >
            {rooms.data?.map((room) => (
              <RoomShowcase
                id={room.id}
                name={room.name}
                description={room.description}
                creatorId={room.creatorId}
                creator={room.creator}
                createdAt={room.createdAt}
                key={room.id}
              />
            ))}
          </ul>
        </div>
      </Layout>
    </>
  );
};

export default Rooms;

const RoomShowcase: React.FC<RoomWithCreatorAndParticipants> = ({
  id,
  name,
  description,
  creatorId,
  creator,
  createdAt,
}: RoomWithCreatorAndParticipants) => {
  return (
    <li
      key={id}
      className="col-span-1 divide-y divide-slate-600 rounded-lg bg-slate-700 shadow"
    >
      <div className="flex w-full items-center justify-between space-x-6 p-6">
        <div className="flex-1 truncate">
          <div className="flex items-center space-x-3">
            <h3 className="truncate text-sm font-medium text-white">{name}</h3>
            <span className="inline-block flex-shrink-0 rounded-full bg-green-100 px-2 py-0.5 text-xs font-medium text-green-800">
              tag
            </span>
          </div>
          <p className="mt-1 truncate text-sm text-white/50">{description}</p>
        </div>
        <img
          className="h-10 w-10 flex-shrink-0 rounded-full bg-gray-300"
          src={creator.image as string}
          alt=""
        />
      </div>
      <Link href={`/rooms/${id}`}>
        <div className="w-full border-t border-slate-600 py-3 text-center text-white">
          <span>Enter Room</span>
        </div>
      </Link>
    </li>
  );
};
